### ISSUE TITLE
Create group error when deploying product

### ISSUE THREAD

**Issue by Madelein-rezco** [alis-x/cli#37]
I am getting the error below in my build logs when trying to deploy my product:
<img width="908" alt="image" src="https://user-images.githubusercontent.com/79693903/163366052-cd628869-020c-42e6-9338-3442cfd88baa.png">

**Comment by jasonbrown-alis** [comment]
@jankrynauw Not sure if this may be a problem, but when I recently created a new neuron, this was in the template:
<img width="1830" alt="image" src="https://user-images.githubusercontent.com/101096256/165088311-6306ea14-bfeb-4547-b782-a61f384865c8.png">

I was getting permission errors when trying to deploy my neuron until I changed it back to what it previously was:
<img width="1830" alt="image" src="https://user-images.githubusercontent.com/101096256/165089302-fe4af50d-910c-4967-bc7d-bdb7706185b9.png">

**Comment by kyle-alis** [comment]
Had the same problem when running `alis product create`.

**Comment by jankrynauw** [comment]
The entity creating the group needs to have permission to create a group - i.e. needs to be a Group Editor in Google Workspace account.
<img width="1649" alt="Screenshot 2022-04-25 at 23 45 20" src="https://user-images.githubusercontent.com/18016598/165180771-97340ba7-64c9-4039-971a-6039d3d9b12b.png">
I've added the following service account:
<img width="1088" alt="Screenshot 2022-04-25 at 23 47 37" src="https://user-images.githubusercontent.com/18016598/165180891-4d4f0c9e-223c-45c8-89e1-8265c6cb2db9.png">

Also, this account also needs to be a billing account user (which already was in place)
<img width="666" alt="Screenshot 2022-04-25 at 23 48 35" src="https://user-images.githubusercontent.com/18016598/165180997-0fec3ff2-1810-47bf-befe-0961d9121d99.png">

The CLI `alis product create...` command display the above requirements once a product has been created.

**Comment by Madelein-rezco** [comment]
Thanks Jan. Was long time period between product create and deploy so think this was an edge case.
